# Generated by Django 5.2.7 on 2025-10-30 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('specialization', models.CharField(choices=[('Yoga', 'Yoga'), ('Strength Training', 'Strength Training'), ('Cardio', 'Cardio'), ('Pilates', 'Pilates'), ('CrossFit', 'CrossFit'), ('Martial Arts', 'Martial Arts'), ('Dance', 'Dance'), ('General Fitness', 'General Fitness')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='gym_app.trainer'),
        ),
    ]
