# Generated by Django 5.2.7 on 2025-10-30 16:26

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0003_member_address_member_alternative_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='height',
        ),
        migrations.RemoveField(
            model_name='member',
            name='weight',
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_end_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 29, 16, 26, 27, 335065, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='ProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=5)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this progress entry', null=True)),
                ('recorded_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='gym_app.member')),
            ],
            options={
                'verbose_name_plural': 'Progress entries',
                'ordering': ['-recorded_date'],
            },
        ),
    ]
