# Generated by Django 5.2.7 on 2025-10-31 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0004_remove_member_height_remove_member_weight_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.RenameField(
            model_name='member',
            old_name='membership_start_date',
            new_name='membership_purchase_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='membership_end_date',
        ),
    ]
